volumes:
    mongo_data:

services:
    catalogdb:
        image: mongo
        container_name: catalogdb
        restart: always
        ports:
        - "27017:27017"
        volumes:
            - mongo_data:/data/db
    
    basketdb:
        image: redis:alpine
        container_name: basketdb
        restart: always
        ports:
        - "6379:6379"

    catalog.api:
        container_name: Catalog.API.api
        restart: always
        build:
            context: .
            dockerfile: ./Catalog.API/Dockerfile
        ports:
            - "5001:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb

    basket.api:
        container_name: Basket.API.api
        restart: always
        build:
            context: .
            dockerfile: ./Basket.API/Dockerfile
        ports:
            - "5002:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basketdb:6379"
        depends_on:
            - basketdb

    gateway.api:
        container_name: Gateway.API.api
        restart: always
        build:
            context: .
            dockerfile: ./Gateway.API/Dockerfile
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ReverseProxy:Clusters:catalog-cluster:Destinations:destination1:Address=catalog.api
            - ReverseProxy:Clusters:basket-cluster:Destinations:destination1:Address=basket.api
        depends_on:
            - catalog.api
            - basket.api